CREATE TABLE "Moodboards" (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    images JSON NOT NULL,
    user_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES "Users"(id)
);

ALTER TABLE "Moodboards"
ADD CONSTRAINT fk_user_id
FOREIGN KEY (user_id)
REFERENCES "Users"(id)
ON DELETE SET NULL;